bind=SUPER+SHIFT,r,reload_config
bind=SUPER+SHIFT,e,quit
bind=SUPER,l,spawn,hyprlock
bind = SUPER,z,spawn,~/.config/rofi/perfect-blue/launcher.sh
bind = SUPER,x,spawn,~/.config/rofi/perfect-blue/powermenu.sh
bind = SUPER,v,spawn,~/.config/rofi/perfect-blue/clipboard.sh
bind = SUPER,h,spawn,~/.local/bin/wallpapers.sh
bind = SUPER,Return,spawn,foot
bind = SUPER+SHIFT,d,spawn,nemo
bind = SUPER,c,spawn,foot -e btop
bind=SUPER,q,killclient
bind=SUPER,left,focusdir,left
bind=SUPER,right,focusdir,right
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down
bind=SUPER,Tab,toggleoverview
bind=SUPER+SHIFT,Tab,focusstack,next
bind=SUPER+SHIFT,left,exchange_client,left
bind=SUPER+SHIFT,down,exchange_client,down
bind=SUPER+SHIFT,up,exchange_client,up
bind=SUPER+SHIFT,right,exchange_client,right
bind=SUPER,space,togglefloating
bind=SUPER,f,togglefullscreen
bind=SUPER+SHIFT,f,togglefakefullscreen
bind=SUPER,m,togglemaximizescreen
bind=SUPER+SHIFT,minus,minimized
bind=SUPER+SHIFT,comma,restore_minimized
bind=SUPER,g,toggleglobal
bind=SUPER,o,toggleoverlay
bind=SUPER,minus,toggle_scratchpad
bind=SUPER+ALT,space,switch_layout
bind=SUPER+ALT,f,set_proportion,1.0
bind=SUPER+ALT,p,switch_proportion_preset
bind=SUPER+ALT,h,spawn,mmsg split h
bind=SUPER+ALT,v,spawn,mmsg split v
bind=SUPER+ALT,equal,incgaps,1
bind=SUPER+ALT,minus,incgaps,-1
bind=SUPER+ALT,g,togglegaps
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0
bind=SUPER+ALT,Left,tagmon,left
bind=SUPER+ALT,Right,tagmon,right
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
bind=SUPER+SHIFT,s,spawn,hyprshot -m region -o ~/Pictures/Screenshots
